export const SELECT_MENU_ITEM = 'SELECT_MENU_ITEM';
export const SELECT_USER = 'SELECT_USER';

export const DESELECT_USER = 'DESELECT_USER';
export const ADD_USER = 'ADD_USER';
export const VALIDATE_ERROR = 'VALIDATE_ERROR';
export const CHANGE_FORM_DATA = 'CHANGE_FORM_DATA';

export const FETCH_CONTACTS_LIST = 'FETCH_CONTACTS_LIST';
export const FETCH_CONTACTS_LIST_SUCCESS = 'FETCH_CONTACTS_LIST_SUCCESS';
export const FETCH_CONTACTS_LIST_ERROR = 'FETCH_CONTACTS_LIST_ERROR';
